In [ ]:
import torch as to
import numpy as np

In [ ]:
a = to.tensor([1,2,3,4,5])
a.size()

torch.Size([5])

In [ ]:
#type of tensor
print(a.type())
#data type of tensor
print(a.dtype)

torch.LongTensor
torch.int64


In [ ]:
#Implicit type conversion
a = to.tensor([1,2,3,4,5],dtype=to.float64)
print(a)
#Explicit type Conversion
a = to.FloatTensor([1,2,2,2])
print(a)
#no of dimension in tensor
print(a.ndimension())
#to convert to 2D
print(a.view(4,1))
print(a.view(-1,1))
print(a.ndimension())

tensor([1., 2., 3., 4., 5.], dtype=torch.float64)
tensor([1., 2., 2., 2.])
1
tensor([[1.],
        [2.],
        [2.],
        [2.]])
tensor([[1.],
        [2.],
        [2.],
        [2.]])
1


In [ ]:
#Conversion of tensor to Numpy
b = a.numpy()
print(b)
c =  to.from_numpy(b)
print(c)
#vector arthematic operations
p = to.tensor([10,2,0,5])
q = to.tensor([20,5,6,2])
print(f"sum of p&q is {p+q}")
print(f"sub of p&q is {p-q}")
print(f"mul of 2p is {2*p}")
print(f"product of p&q is {p*q}")
print(f"dot product of p&q is {to.dot(p,q)}")


[1. 2. 2. 2.]
tensor([1., 2., 2., 2.])
sum of p&q is tensor([30,  7,  6,  7])
sub of p&q is tensor([-10,  -3,  -6,   3])
mul of 2p is tensor([20,  4,  0, 10])
product of p&q is tensor([200,  10,   0,  10])
dot product of p&q is 220


In [ ]:
#line space in tensor
print(to.linspace(-2,2,steps=6))

tensor([-2.0000, -1.2000, -0.4000,  0.4000,  1.2000,  2.0000])
